version: '3.1'
services:
  corkboard:
    image: node:10-alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    command: "npm run dev"
    volumes:
      - ./:/home/node/app
    ports: 
      - 3000:3000
    networks:
      cb-net:
        aliases: 
          - corkboard.dev.local

  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: corkboard
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: corkboard
    ports: 
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      cb-net:
        aliases: 
          - db1.corkboard.dev.local

  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - ./fakes3:/fakes3_root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      cb-net:
        aliases: 
          - adminer.corkboard.dev.local

  redis:
    image: redis
    networks:
      cb-net:
        aliases: 
          - redis1.corkboard.dev.local

volumes: 
  db-data: {}

networks: 
  cb-net:
    driver: bridge