version: '3.1'
services:
  app:
    image: node:10-alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PGHOST=db1.corkboard.dev.local
      - PGUSER=corkboard
      - PGDATABASE=corkboard
      - PGPASSWORD=passw0rd
      - PGPORT=5432
    command: "npm run dev"
    volumes:
      - ./:/home/node/app
    ports: 
      - 3000:3000
    networks:
      cb-net:
        aliases: 
          - corkboard.dev.local

  database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: corkboard
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: corkboard
    ports: 
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      cb-net:
        aliases: 
          - db1.corkboard.dev.local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      cb-net:
        aliases: 
          - adminer.corkboard.dev.local

  redis:
    image: redis
    networks:
      cb-net:
        aliases: 
          - redis1.corkboard.dev.local

volumes: 
  db-data: {}

networks: 
  cb-net:
    driver: bridge